name: Build Book and Upload Artifacts

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Crowbook
        run: cargo install crowbook

      - name: Prepare output folder
        run: |
          rm -rf output
          mkdir output

      - name: Combine all Markdown into book.md (in order)
        run: |
          # You can change the order here if needed
          cat *.md > book.md

      - name: Generate EPUB, PDF, and HTML
        run: |
          crowbook --to epub --output output/book.epub book.md
          crowbook --to pdf  --output output/book.pdf  book.md
          crowbook --to html --output output/book.html book.md

      - name: Upload output files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sribook-outputs
          path: output/
