name: Build Book with Crowbook

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust and Crowbook
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          cargo install crowbook --version 0.16.0

      - name: Create properly formatted book.md
        run: |
          # Create valid YAML metadata block
          cat > book.md << 'EOF'
          ---
          title: "Generated Book"
          author: "GitHub Actions"
          lang: en
          ---
          
          EOF
          
          # Append all markdown content (excluding any existing YAML blocks)
          for file in *.md; do
            if [ "$file" != "book.md" ]; then
              # Skip YAML frontmatter if present in source files
              sed '1{/^---/!q;};1,/^---/d' "$file" >> book.md
              echo -e "\n" >> book.md
            fi
          done
          
          echo "First 20 lines of book.md:"
          head -n 20 book.md

      - name: Generate outputs
        run: |
          mkdir -p output
          echo "Generating outputs..."
          
          # Generate each format with error logging
          crowbook --to epub --output output/book.epub book.md 2> epub_errors.txt || echo "EPUB generation had warnings"
          crowbook --to pdf --output output/book.pdf book.md 2> pdf_errors.txt || echo "PDF generation had warnings"
          crowbook --to html --output output/book.html book.md 2> html_errors.txt || echo "HTML generation had warnings"
          
          echo "Generated files:"
          ls -la output/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: book-artifacts
          path: |
            output/*
            *.txt
            book.md
          retention-days: 1
