name: Build Single Book from All Markdown

on:
  push:
    branches: [main]

jobs:
  build-book:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Crowbook
        run: cargo install crowbook

      - name: Clean output
        run: |
          rm -rf output
          mkdir output

      - name: Combine all Markdown files into one
        run: |
          cat *.md > book.md

      - name: Generate EPUB, PDF, and HTML
        run: |
          crowbook --to epub --output output/book.epub book.md
          crowbook --to pdf  --output output/book.pdf  book.md
          crowbook --to html --output output/book.html book.md

      - name: Commit and push outputs
        run: |
          git pull origin main
          git add output/
          git commit -m "📘 Combined book from all .md files"
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
