name: Build Book Without YAML

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust and Crowbook
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          cargo install crowbook --version 0.16.0

      - name: Create clean book.md
        run: |
          # Start with simple header
          echo "# My Generated Book" > book.md
          echo "" >> book.md
          
          # Append all markdown content (excluding README.md)
          for file in *.md; do
            if [ "$file" != "README.md" ] && [ "$file" != "book.md" ]; then
              # Remove any YAML blocks
              sed -e '/^---/,/^---/d' "$file" >> book.md
              echo "" >> book.md  # Add spacing
            fi
          done

      - name: Generate outputs
        run: |
          mkdir -p output
          
          # Correct syntax: --set key=value (no spaces)
          crowbook --to epub output/book.epub book.md \
            --set metadata.title="My Book" \
            --set metadata.author="Auto-generated" \
            --set metadata.lang="en"
          
          crowbook --to pdf output/book.pdf book.md \
            --set metadata.title="My Book" \
            --set metadata.author="Auto-generated" \
            --set metadata.lang="en"
          
          crowbook --to html output/book.html book.md \
            --set metadata.title="My Book" \
            --set metadata.author="Auto-generated" \
            --set metadata.lang="en"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: book-outputs
          path: output/
          retention-days: 1
