name: Build Book with Crowbook

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          # Install Rust
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          
          # Install Crowbook
          cargo install crowbook --version 0.16.0
          
          # Install yq for YAML processing
          sudo apt-get update && sudo apt-get install -y jq

      - name: Create book.md with validated metadata
        run: |
          # Create minimal valid YAML header
          cat > book.md << 'EOF'
          ---
          title: "Generated Book"
          author: "GitHub Actions"
          lang: "en"
          ---
          
          EOF
          
          # Append content from other markdown files (skipping existing YAML blocks)
          for file in *.md; do
            if [ "$file" != "book.md" ]; then
              # Skip lines between --- markers (existing YAML blocks)
              awk 'BEGIN {y=0} /^---/ {y++; next} y!=1' "$file" >> book.md
              echo -e "\n" >> book.md
            fi
          done
          
          # Simple YAML validation by extracting the block
          echo "Extracted YAML metadata:"
          awk '/^---/{flag=!flag; next} flag' book.md
          
          # Verify the YAML block ends properly
          if [ $(grep -c '^---$' book.md) -ne 2 ]; then
            echo "ERROR: YAML block must be enclosed by --- markers"
            echo "Current file start:"
            head -n 10 book.md
            exit 1
          fi

      - name: Generate outputs
        run: |
          mkdir -p output
          echo "Generating outputs..."
          
          # Generate each format with error logging
          crowbook --to epub --output output/book.epub book.md 2> epub_errors.txt || echo "EPUB generation completed with warnings"
          crowbook --to pdf --output output/book.pdf book.md 2> pdf_errors.txt || echo "PDF generation completed with warnings"
          crowbook --to html --output output/book.html book.md 2> html_errors.txt || echo "HTML generation completed with warnings"
          
          # Basic output verification
          echo "Generated files:"
          ls -la output/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: book-artifacts
          path: |
            output/*
            *.txt
            book.md
          retention-days: 1
