name: Build Book and Upload Artifacts

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust and Crowbook
        run: |
          # Install Rust
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          
          # Install Crowbook with version check
          cargo install crowbook
          crowbook --version

      - name: Debug - Show repository structure
        run: |
          echo "Repository contents:"
          ls -la
          echo "Markdown files:"
          ls *.md || echo "No markdown files found"

      - name: Create combined book.md
        run: |
          # Create combined markdown file with header
          echo "# Generated Book\n" > book.md
          cat *.md >> book.md 2>/dev/null || echo "Warning: No markdown files to combine"
          
          echo "First 10 lines of book.md:"
          head -n 10 book.md
          echo "File size:"
          ls -lh book.md

      - name: Generate outputs
        run: |
          mkdir -p output
          
          echo "Generating EPUB..."
          if ! crowbook --to epub --output output/book.epub book.md; then
            echo "EPUB generation failed. Showing errors:"
            crowbook --to epub --output output/book.epub book.md 2>&1 | grep -i error || true
            echo "Last 20 lines of book.md:"
            tail -n 20 book.md
          else
            echo "EPUB generated successfully"
          fi
          
          echo "Generating PDF..."
          crowbook --to pdf --output output/book.pdf book.md || echo "PDF generation failed"
          
          echo "Generating HTML..."
          crowbook --to html --output output/book.html book.md || echo "HTML generation failed"
          
          echo "Generated files:"
          ls -la output/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: book-outputs
          path: |
            output/*
            book.md
          if-no-files-found: warn
