name: Build Crowbook Book

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Crowbook
        run: cargo install crowbook

      - name: Create output directory
        run: mkdir output

      - name: Generate EPUB
        run: crowbook --to epub --output output/book.epub book.md

      - name: Generate PDF
        run: crowbook --to pdf --output output/book.pdf book.md

      - name: Generate HTML
        run: crowbook --to html --output output/book.html book.md

      - name: Upload all ebook outputs
        uses: actions/upload-artifact@v4
        with:
          name: book-formats
          path: output/
